Container handler
kubescape/sniffer pull request #9
Opened 2023-02-23 15:04 UTC by rcohencyberarmor

## Overview

container handling implementation:
we are going to monitor any new containers and collect realtime information for filter the SBOM

2023-03-01 12:07 UTC, matthyx commented
@rcohencyberarmor can you rebase now that your other PR has merged?

2023-03-01 15:13 UTC, matthyx requested changes
it seems the rebase didn't work, or your previous PR didn't merge, I still see snake case

2023-03-01 15:13 UTC, matthyx commented on pkg/config/config.go
> +	return os.LookupEnv(CONFIG_ENV_VAR)
are you sure it was rebased correctly? I think this was fixed in your previous PR?

2023-03-02 07:54 UTC, dwertent commented
This was not rebased well.

2023-03-02 07:56 UTC, dwertent commented
Please open a new branch from the main branch.

2023-03-02 07:56 UTC, closed without merging